core_folder/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('user/', include('account.urls')),
    path('orders/', include('orders.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'account.views.handle_not_fount'

orders/urls.py
from django.urls import path

from orders import views

urlpatterns = [
    path('proceed-to-checkout', views.checkout, name='checkout'),
    path('handle-request', views.handle_request, name='handle_request'),
    path('my-orders', views.orders, name='orders'),
    path('my-orders/<int:o_id>', views.order_detail, name='order_detail'),
    path('generate-invoice/<int:o_id>/Payment-Invoice', views.generate_invoice, name='generate_invoice'),
]

products/urls.py
from django.urls import path
from django.views.generic import TemplateView

from products import views

app_name = 'products'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('categories/', TemplateView.as_view(template_name='products/categories.html'), name='category'),
    path('category/<slug:category_slug>/', views.product_list, name='products-list'),
    path('product/<slug:c_slug>/<slug:p_slug>/', views.details_of_product, name='category'),
    path('cart/', views.cart, name='cart'),
    path('add-to-cart/', views.add_to_cart, name='add_to_cart'),
    path('minus-from-cart/', views.minus_from_cart, name='minus_from_cart'),
    path('remove-from-cart/<str:p_id>/', views.remove_from_cart, name='remove_from_cart'),
]

account/models.py
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.db import models


class MyAccountManager(BaseUserManager):
    def create_user(self, username, email, password=None):
        if not email:
            raise ValueError('user must have email address')

        if not username:
            raise ValueError('User must have a username')

        user = self.model(
            email=self.normalize_email(email),
            username=username,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password):
        user = self.create_user(
            email=self.normalize_email(email),
            username=username,
            password=password,
        )

        user.is_admin = True
        user.is_active = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class CustomUser(AbstractBaseUser, PermissionsMixin):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    username = models.CharField(max_length=50, unique=True)
    email = models.EmailField(max_length=100, unique=True)
    phone_number = models.CharField(max_length=10)

    created_at = models.DateTimeField(auto_now_add=True)
    last_login = models.DateTimeField(auto_now=True)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    objects = MyAccountManager()

    def __str__(self):
        return self.get_full_name()

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, add_labal):
        return True

    def get_full_name(self):
        full_name = "%s %s" % (self.first_name, self.last_name)
        return full_name.strip()


class Address(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    state = models.CharField(max_length=50)
    district = models.CharField(max_length=50)
    locality = models.CharField(max_length=50)
    pin_code = models.PositiveIntegerField()
    phone_number = models.CharField(max_length=20)
    is_available = models.BooleanField(default=True)

    def __str__(self):
        return str(self.user) + '|' + str(self.locality)

templates/partials/_localities.html
<div class="form-group">
    <label for="id_locality">Nearest Location:</label>
    <select class="form-control" id="id_locality" name="locality">
        <option disabled selected>Select nearest location from this list.</option>
        {% for locality in localities %}
        <option value="{{ locality }}">{{ locality }}</option>
        {% endfor %}
    </select>
</div>

templates/partials/_messages.html
{% if messages %}
{% for message in messages %}
<div class="alert w-50 m-auto alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %}"
     role="alert">
    {{ message }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endfor %}
{% endif %}

templates/partials/add_wishlist.html
<script>
    $(document).ready(function() {
        console.log("function ready");
        $(".addWishlist").click(function() {
            console.log("function called");
            var _prodId = $(this).attr('data-id');
            var _url = '{% url "add_wishlist" %}';
            var _redirectUrl = '{% url "wishlist" %}';

            console.log(_redirectUrl)
            console.log(_url)
            console.log(_prodId)

            $.ajax({
                url:_url,
                data:{
                    prod_id:_prodId
                },
                dataType:'json',
                success:function(res){
                    if((res.data) == 1 ){
                        window.location = _redirectUrl;
                    } else {
                        alert("item already in your wishlist..!");
                    }
                }
            })
        });
    });
</script>

templates/partials/footer.html
<footer class="bg-dark text-white">
    <div class="container py-4">
        <div class="row py-5">
            <div class="col-md-4 mb-md-0">
                <h6 class="text-uppercase mb-3">Customer services</h6>
                <ul class="list-unstyled mb-0">
                    <li><a class="footer-link" href="#">Help &amp; Contact Us</a></li>
                    <li><a class="footer-link" href="#">Returns &amp; Refunds</a></li>
                    <li><a class="footer-link" href="#">Online Stores</a></li>
                    <li><a class="footer-link" href="#">Terms &amp; Conditions</a></li>
                </ul>
            </div>
            <div class="col-md-4 mb-3 mb-md-0">
                <h6 class="text-uppercase mb-3">Company</h6>
                <ul class="list-unstyled mb-0">
                    <li><a class="footer-link" href="#">What We Do</a></li>
                    <li><a class="footer-link" href="#">Available Services</a></li>
                    <li><a class="footer-link" href="#">Latest Posts</a></li>
                    <li><a class="footer-link" href="#">FAQs</a></li>
                </ul>
            </div>
            <div class="col-md-4">
                <h6 class="text-uppercase mb-3">Social media</h6>
                <ul class="list-unstyled mb-0">
                    <li><a class="footer-link" href="#">Twitter</a></li>
                    <li><a class="footer-link" href="#">Instagram</a></li>
                    <li><a class="footer-link" href="#">Tumblr</a></li>
                    <li><a class="footer-link" href="#">Pinterest</a></li>
                </ul>
            </div>
        </div>
        <div class="pt-4"></div>
    </div>
</footer>

templates/partials/navbar.html
{% load static %}

<!-- navbar-->
<header class="header bg-white">
    <div class="container px-0 px-lg-3">
        <nav class="navbar navbar-expand-lg navbar-light py-3 px-lg-0">
            <a class="navbar-brand" href="{% url 'products:home' %}">
                <span class="font-weight-bold text-uppercase text-dark">digital ground</span>
            </a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                    data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <!-- Link-->
                        {% url 'products:home' as home %}
                        <a class="nav-link {% if request.path == home %}active{% endif %}"
                           href="{% url 'products:home' %}">Home</a>
                    </li>
                    <li class="nav-item dropdown">
                        {% url 'products:category' as categ %}
                        <a class="nav-link dropdown-toggle {% if request.path == categ %}active{% endif %}"
                           id="pagesDropdown" href="#"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Categories</a>
                        <div class="dropdown-menu mt-3" aria-labelledby="pagesDropdown">
                            {% if categories_obj %}
                                {% for category in categories_obj %}
                                <a class="dropdown-item border-0 transition-link text-capitalize"
                                   href="{% url 'products:products-list' category.slug %}">{{ category.title }}
                                </a>
                                {% endfor %}
                            {% endif %}
                            <hr>
                            <a class="dropdown-item border-0 transition-link" href="{% url 'products:category' %}">
                                All Categories
                            </a>
                        </div>
                    </li>
                </ul>

                {% if request.user.is_authenticated %}
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'products:cart' %}">
                            <i class="fas fa-cart-plus mr-1 text-gray"></i>
                            Cart
                            {% if request.session.cart_length %}
                            <span class="text-primary">({{ request.session.cart_length }})</span>
                            {% else %}
                            <span class="text-primary">(0)</span>
                            {% endif %}
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'wishlist' %}">
                            <i class="fas fa-heart mr-1 text-gray"></i>
                            <span class="text-primary">({{ wishlist_len }})</span>
                        </a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="pagesDropdownProfile" href="#"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-user-alt mr-1 text-gray"></i>
                            Account
                        </a>

                        <div class="dropdown-menu mt-3" aria-labelledby="pagesDropdownProfile">
                            <a class="dropdown-item border-0 transition-link" href="{% url 'profile' %}">
                                Profile
                            </a>
                            <a class="dropdown-item border-0 transition-link" href="{% url 'products:cart' %}">Cart</a>
                            <a class="dropdown-item border-0 transition-link" href="{% url 'orders' %}">
                                Orders
                            </a>
                            <a class="dropdown-item border-0 transition-link"
                               href="{% url 'password_change' %}">
                                Change Password
                            </a>
                            <hr>
                            <a class="dropdown-item border-0 transition-link" href="{% url 'logout' %}">
                                Log Out
                            </a>
                        </div>
                    </li>
                </ul>
                {% else %}
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'products:cart' %}">
                            <i class="fas fa-cart-plus mr-1 text-gray"></i>
                            Cart
                            {% if request.session.cart_length %}
                            <span class="text-primary">({{ request.session.cart_length }})</span>
                            {% else %}
                            <span class="text-primary">(0)</span>
                            {% endif %}
                        </a>
                    </li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">Login</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'register' %}">Create Account</a></li>
                </ul>
                {% endif %}
            </div>
        </nav>
    </div>
</header>

templates/partials/scripts.html
{% load static %}

<!-- JavaScript files-->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'vendor/lightbox2/js/lightbox.min.js' %}"></script>
<script src="{% static 'vendor/nouislider/nouislider.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap-select/js/bootstrap-select.min.js' %}"></script>
<script src="{% static 'vendor/owl.carousel2/owl.carousel.min.js' %}"></script>
<script src="{% static 'vendor/owl.carousel2.thumbs/owl.carousel2.thumbs.min.js' %}"></script>
<script src="{% static 'js/front.js' %}"></script>

<script>
        var range = document.getElementById('range');
        noUiSlider.create(range, {
            range: {
                'min': 0,
                'max': 2000
            },
            step: 5,
            start: [100, 1000],
            margin: 300,
            connect: true,
            direction: 'ltr',
            orientation: 'horizontal',
            behaviour: 'tap-drag',
            tooltips: true,
            format: {
              to: function ( value ) {
                return '$' + value;
              },
              from: function ( value ) {
                return value.replace('', '');
              }
            }
        });

        // ------------------------------------------------------- //
        //   Inject SVG Sprite - 
        //   see more here 
        //   https://css-tricks.com/ajaxing-svg-sprite/
        // ------------------------------------------------------ //
        function injectSvgSprite(path) {
        
            var ajax = new XMLHttpRequest();
            ajax.open("GET", path, true);
            ajax.send();
            ajax.onload = function(e) {
            var div = document.createElement("div");
            div.className = 'd-none';
            div.innerHTML = ajax.responseText;
            document.body.insertBefore(div, document.body.childNodes[0]);
            }
        }
        // this is set to BootstrapTemple website as you cannot 
        // inject local SVG sprite (using only 'icons/orion-svg-sprite.svg' path)
        // while using file:// protocol
        // pls don't forget to change to your domain :)
        injectSvgSprite('https://bootstraptemple.com/files/icons/orion-svg-sprite.svg'); 
        

</script>

<!-- FontAwesome CSS - loading as last, so it doesn't block rendering-->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css"
      integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">