core_folder/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('user/', include('account.urls')),
    path('orders/', include('orders.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'account.views.handle_not_fount'

orders/urls.py
from django.urls import path

from orders import views

urlpatterns = [
    path('proceed-to-checkout', views.checkout, name='checkout'),
    path('handle-request', views.handle_request, name='handle_request'),
    path('my-orders', views.orders, name='orders'),
    path('my-orders/<int:o_id>', views.order_detail, name='order_detail'),
    path('generate-invoice/<int:o_id>/Payment-Invoice', views.generate_invoice, name='generate_invoice'),
]

products/urls.py
from django.urls import path
from django.views.generic import TemplateView

from products import views

app_name = 'products'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('categories/', TemplateView.as_view(template_name='products/categories.html'), name='category'),
    path('category/<slug:category_slug>/', views.product_list, name='products-list'),
    path('product/<slug:c_slug>/<slug:p_slug>/', views.details_of_product, name='category'),
    path('cart/', views.cart, name='cart'),
    path('add-to-cart/', views.add_to_cart, name='add_to_cart'),
    path('minus-from-cart/', views.minus_from_cart, name='minus_from_cart'),
    path('remove-from-cart/<str:p_id>/', views.remove_from_cart, name='remove_from_cart'),
]

products/models.py
from django.db import models
from django.urls import reverse

from account.models import CustomUser


class Category(models.Model):
    title = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=50, unique=True)
    image = models.ImageField(upload_to='category', null=True)

    def __str__(self):
        return self.title

    def get_url(self):
        return reverse('products:products-list', args=[self.slug])


class Brand(models.Model):
    name = models.CharField(max_length=20)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Product(models.Model):
    title = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50, unique=True)
    image = models.ImageField(upload_to='gallery', null=True, blank=True)
    image1 = models.ImageField(upload_to='gallery', null=True, blank=True)
    image2 = models.ImageField(upload_to='gallery', null=True, blank=True)
    image3 = models.ImageField(upload_to='gallery', null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE, null=True)
    description = models.TextField()
    price = models.DecimalField(max_digits=6, decimal_places=2)
    stock = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.title) + '|' + str(self.brand)

    def get_url(self):
        return reverse('products:category', args=[self.category.slug, self.slug])


class Cart(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    updated_at = models.DateTimeField(auto_now=True)

    def item_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return str(self.product.title) + '|' + str(self.user)


class Wishlist(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)

    class Meta:
        unique_together = ("product", 'user')

    def __str__(self):
        return str(self.product.title) + '|' + str(self.user)

products/views.py
from django.contrib import messages
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import TemplateView, ListView

from account.models import Address
from products.models import Category, Product, Brand, Cart


class HomeView(TemplateView):
    template_name = 'products/home.html'

    def get_context_data(self, **kwargs):
        context = {
            'categories': Category.objects.all().order_by('?')[:3],  # fetching 3 random objects
            'products': Product.objects.all().order_by('?')[:8]
        }
        return context


class ProductListView(ListView):
    model = Product
    context_object_name = 'products'
    template_name = 'products/category_products.html'
    category = None

    def get_queryset(self):
        self.category = get_object_or_404(Category, slug=self.kwargs.get('slug'))
        return super().get_queryset().filter(Q(category=self.category) & Q(stock__gte=1))  # stock >= 1

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['category'] = self.category
        context['brands'] = Brand.objects.filter(category=self.category)
        return context


def product_filter(*args, **kwargs):
    selected_brands = kwargs['data']['selected_brands']
    sort_method = kwargs['data']['sort_method']
    min_price = kwargs['data']['min_price']
    max_price = kwargs['data']['max_price']
    products = args[0]

    if len(selected_brands) != 0:
        selected_brands_objs = list()
        for brand in selected_brands:
            selected_brands_objs.append(get_object_or_404(Brand, name=brand))
        products = products.filter(brand__in=selected_brands_objs)

    if sort_method:
        if sort_method == '1':
            products = products.order_by('price')
        elif sort_method == '2':
            products = products.order_by('-price')

    if min_price:
        products = products.filter(price__gte=min_price)
    if max_price:
        products = products.filter(price__lte=max_price)

    return products


def product_list(request, category_slug):
    category = get_object_or_404(Category, slug=category_slug)
    products = Product.objects.filter(Q(category=category) & Q(stock__gte=1))
    brands = Brand.objects.filter(category=category)
    category_id = category.id

    context = dict()

    # filtering the products
    if request.method == 'POST':
        selected_brands = request.POST.getlist('brands')
        sort_method = request.POST['sort']
        min_price = request.POST['min']
        max_price = request.POST['max']

        prod_filter = {
            'cat_id': category_id,
            'selected_brands': selected_brands,
            'sort_method': sort_method,
            'min_price': min_price,
            'max_price': max_price
        }
        context.update(prod_filter)

        # filtering the products
        products = product_filter(products, data=prod_filter)

        request.session['prod_filter'] = prod_filter

    # this block is used to filter the data when pagination is occurs...(when changing pages)
    if request.method == 'GET':
        if 'prod_filter' in request.session:
            if request.session['prod_filter']['cat_id'] == category_id:
                prod_filter = request.session['prod_filter']
                context.update(prod_filter)
                # filtering the products
                products = product_filter(products, data=prod_filter)
            else:
                del request.session['prod_filter']
        try:
            if request.GET['clear_filter'] == '1':
                # clearing filter and reset to default products fetching
                request.session.flush()
                context.pop('cat_id')
                context.pop('selected_brands')
                context.pop('sort_method')
                context.pop('min_price')
                context.pop('max_price')
                products = Product.objects.filter(Q(category=category) & Q(stock__gte=1))
        except:
            pass

    # Pagination
    paginator = Paginator(products, 3)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context.update({
        'category': category,
        'page_obj': page_obj,
        'brands': brands
    })
    return render(request, 'products/category_products.html', context)


def details_of_product(request, c_slug, p_slug):
    product = get_object_or_404(Product, slug=p_slug)
    related_products = Product.objects.exclude(id=product.id).filter(category__slug=c_slug)

    context = {
        'product': product,
        'related_products': related_products
    }
    return render(request, 'products/detail.html', context)


def cart(request):
    cart_obj = list()
    total_price = 0
    context = {}

    if request.user.is_authenticated:
        products = Cart.objects.filter(user=request.user)
        for i in products:
            total = int(i.item_total())
            product = get_object_or_404(Product, id=i.product.id)
            temp = {
                'product': product,
                'qty': i.quantity,
                'total': total
            }
            total_price += total
            cart_obj.append(temp)
        request.session['cart_length'] = Cart.objects.filter(user=request.user).count()
        addresses = Address.objects.filter(user=request.user)
        context = {'addresses': addresses}

    else:
        # request.session.flush()
        if 'cart' in request.session:
            session_cart = request.session['cart']
            for i in session_cart:
                item = session_cart[i]
                product = get_object_or_404(Product, id=i)
                quantity = item['qty']
                total = product.price * int(quantity)
                temp = {
                    'product': product,
                    'qty': quantity,
                    'total': total
                }
                total_price += total
                cart_obj.append(temp)
                print(cart_obj)

            request.session['cart_length'] = len(request.session['cart'])

    if len(cart_obj) < 1:
        context = None
    else:
        tax = total_price * 3 / 100  # 3% tax
        shipping_charge = 40
        discount = total_price * 2 / 100  # 2% discount
        grand_total = total_price + tax + shipping_charge - discount

        context['cart_obj'] = cart_obj
        context['total_price'] = total_price
        context['tax'] = tax
        context['shipping_charge'] = shipping_charge
        context['discount'] = discount
        context['grand_total'] = grand_total

    return render(request, 'products/cart.html', {'cart_products': context})


def add_to_cart(request):
    prod_id = request.POST['prod_id']
    try:
        qty = request.POST['quantity']
    except:
        qty = 1

    if request.user.is_authenticated:
        product = get_object_or_404(Product, id=prod_id)
        if Cart.objects.filter(product=prod_id, user=request.user).exists():
            item = Cart.objects.get(product=prod_id, user=request.user)
            item.quantity += int(qty)
        else:
            item = Cart.objects.create(
                product=product,
                user=request.user,
                quantity=int(qty)
            )
        item.save()

    else:
        item = dict()
        item[prod_id] = {
            'qty': qty
        }

        if 'cart' in request.session:
            session_cart = request.session['cart']
            if prod_id in request.session['cart']:
                qty_in_session = int(session_cart[prod_id]['qty'])
                session_cart[prod_id]['qty'] = qty_in_session + int(qty)
                request.session['cart'] = session_cart
            else:
                session_cart.update(item)
                request.session['cart'] = session_cart
        else:
            request.session['cart'] = item

        request.session['cart_length'] = len(request.session['cart'])

    messages.success(request, 'Item added to the cart.')
    return redirect('products:cart')


def minus_from_cart(request):
    try:
        prod_id = request.POST['prod_id']
        if request.user.is_authenticated:
            item = Cart.objects.get(product=prod_id, user=request.user)
            item.quantity -= 1
            item.save()
            if item.quantity < 1:
                item.delete()

        else:
            session_cart = request.session['cart']
            qty_in_session = int(session_cart[prod_id]['qty'])
            session_cart[prod_id]['qty'] = qty_in_session - 1
            if session_cart[prod_id]['qty'] < 1:
                del session_cart[prod_id]
            request.session['cart'] = session_cart
    except:
        pass

    return redirect('products:cart')


def remove_from_cart(request, p_id):
    if request.user.is_authenticated:
        item = Cart.objects.get(product=p_id, user=request.user)
        item.delete()
    else:
        session_cart = request.session['cart']
        del session_cart[p_id]
        request.session['cart'] = session_cart
    messages.error(request, 'Item remove from your cart.')
    return redirect('products:cart')

templates/products/cart.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block content %}
<div class="container">
    <!-- HERO SECTION-->
    <section class="py-5 bg-light">
        <div class="container">
            <div class="row px-4 px-lg-5 py-lg-4 align-items-center">
                <div class="col-lg-6">
                    <h1 class="h2 text-uppercase mb-0">Cart</h1>
                </div>
                <div class="col-lg-6 text-lg-right">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb justify-content-lg-end mb-0 px-0">
                            <li class="breadcrumb-item"><a href="{% url 'products:home' %}">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Cart</li>
                        </ol>
                    </nav>
                </div>
            </div>
            {% include 'partials/_messages.html' %}
        </div>
    </section>

    {% if cart_products %}
    <section class="py-5">
        <h2 class="h5 text-uppercase mb-4">Shopping cart</h2>

        <div class="row">
            <div class="col-lg-8 mb-4 mb-lg-0">
                <!-- CART TABLE-->
                <div class="table-responsive mb-4">
                    <table class="table">
                        <thead class="bg-light">
                        <tr>
                            <th class="border-0" scope="col">#</th>
                            <th class="border-0" scope="col">
                                <strong class="text-small text-uppercase">Product</strong>
                            </th>
                            <th class="border-0" scope="col">
                                <strong class="text-small text-uppercase">Price</strong>
                            </th>
                            <th class="border-0" scope="col">
                                <strong class="text-small text-uppercase">Quantity</strong>
                            </th>
                            <th class="border-0" scope="col">
                                <strong class="text-small text-uppercase">Total</strong>
                            </th>
                            <th class="border-0" scope="col"></th>
                        </tr>
                        </thead>

                        <tbody>
                        {% for cart_product in cart_products.cart_obj %}
                        <tr>
                            <td class="align-middle border-0">
                                <strong class="mb-0">{{ forloop.counter }}</strong>
                            </td>
                            <th class="pl-0 border-0" scope="row">
                                <div class="media align-items-center">

                                    {% if cart_product.product.image %}
                                    <a class="reset-anchor d-block animsition-link"
                                       href="{{ cart_product.product.get_url }}">
                                        <img src="{{cart_product.product.image.url}}"
                                             alt="{{cart_product.product.title}}"
                                             width="70"/>
                                    </a>
                                    {% else %}
                                    <a class="reset-anchor d-block animsition-link"
                                       href="{{ cart_product.get_url }}">
                                        <img src="{% static 'img/product-detail-3.jpg' %}"
                                             alt="{{cart_product.title}}" width="70"/>
                                    </a>
                                    {% endif %}

                                    <div class="media-body ml-3">
                                        <strong class="h6">
                                            <a class="reset-anchor animsition-link" href="{{ cart_product.get_url }}">
                                                {{cart_product.product.title}}
                                            </a>
                                        </strong>
                                    </div>
                                </div>
                            </th>
                            <td class="align-middle border-0">
                                <p class="mb-0 small">{{cart_product.product.price}} &#x20B9</p>
                            </td>
                            <td class="align-middle border-0">
                                <div class="border d-flex align-items-center justify-content-between px-3">
                                    <span class="small text-uppercase text-gray headings-font-family">Quantity</span>
                                    <div class="quantity">

                                        <form action="{% url 'products:minus_from_cart' %}" method="post">
                                            {% csrf_token %}
                                            <input type="hidden" name="prod_id" value="{{ cart_product.product.id }}">
                                            <button type="submit" class="p-0 text-primary">
                                                <i class="fas fa-minus"></i>
                                            </button>
                                        </form>

                                        <input class="form-control form-control-sm border-0 shadow-0 p-0"
                                               type="text" value="{{ cart_product.qty }}"/>

                                        <form action="{% url 'products:add_to_cart' %}" method="post">
                                            {% csrf_token %}
                                            <input type="hidden" name="prod_id" value="{{ cart_product.product.id }}">
                                            <button type="submit" class="p-0 text-primary">
                                                <i class="fas fa-plus"></i>
                                            </button>
                                        </form>

                                    </div>
                                </div>
                            </td>
                            <td class="align-middle border-0">
                                <p class="mb-0 small">{{ cart_product.total|floatformat:2|intcomma }} &#x20B9</p>
                            </td>
                            <td class="align-middle border-0">
                                <a class="reset-anchor"
                                   href="{% url 'products:remove_from_cart' cart_product.product.id %}">
                                    <i class="fas fa-trash-alt small text-muted"></i>
                                </a>
                            </td>
                        </tr>
                        {% endfor %}

                        </tbody>
                    </table>
                </div>
                <!-- CART NAV-->
                <div class="bg-light px-4 py-3">
                    <div class="row align-items-center text-center">
                        <div class="col-md-6 mb-3 mb-md-0 text-md-left">
                            <a class="btn btn-link p-0 text-dark btn-sm" href="{% url 'products:category' %}">
                                <i class="fas fa-long-arrow-alt-left mr-2"></i>
                                Continue shopping
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- ORDER TOTAL-->
            <div class="col-lg-4">
                <div class="card border-0 rounded-0 p-lg-4 bg-light">
                    <div class="card-body">
                        <h5 class="text-uppercase mb-4">Cart total</h5>
                        <ul class="list-unstyled">
                            <li class="d-flex align-items-center justify-content-between">
                                <strong class="text-uppercase small font-weight-bold">Subtotal</strong>
                                <span class="text-muted small">
                                    {{ cart_products.total_price|floatformat:2|intcomma }}
                                </span>
                            </li>
                            <li class="d-flex align-items-center justify-content-between">
                                <strong class="text-uppercase small font-weight-bold">Shipping Charge</strong>
                                <span class="text-muted small">
                                    + {{ cart_products.shipping_charge|floatformat:2|intcomma }}
                                </span>
                            </li>
                            <li class="d-flex align-items-center justify-content-between">
                                <strong class="text-uppercase small font-weight-bold">Tax</strong>
                                <span class="text-muted small">
                                    + {{ cart_products.tax|floatformat:2|intcomma }}
                                </span>
                            </li>
                            <li class="d-flex align-items-center justify-content-between">
                                <strong class="text-uppercase small font-weight-bold">Discount</strong>
                                <span class="text-muted small">
                                    - {{ cart_products.discount|floatformat:2|intcomma }}
                                </span>
                            </li>
                            <li class="border-bottom my-2"></li>
                            <li class="d-flex align-items-center justify-content-between mb-4">
                                <strong class="text-uppercase small font-weight-bold">Total</strong>
                                <strong>{{ cart_products.grand_total|floatformat:2|intcomma }} &#x20B9</strong>
                            </li>
                        </ul>

                        {% if request.user.is_authenticated %}
                        {% if cart_products.addresses %}
                        <hr>
                        <strong class="text-uppercase text-sm">
                            <u>Select&nbspShipping&nbspAddress</u>
                        </strong>

                        <form action="{% url 'checkout' %}" id="myform" class="mt-2" method="get">
                            {% for address in cart_products.addresses %}
                            <div class="mb-3 border px-2 shadow">
                                <input type="radio" name="address" value="{{address.id}}"
                                       class="address" id="id_{{address.id}}">
                                <strong>Address {{forloop.counter}}</strong><br>
                                <label class="px-3" for="id_{{address.id}}" style="cursor:pointer">
                                    {{address.phone_number}}
                                    {{address.locality}},&nbsp{{address.district}}<br>
                                    {{address.state}},&nbsp{{address.pin_code}}<br>
                                </label>
                            </div>
                            {% endfor %}

                            <button type="submit" class="btn btn-dark btn-lg btn-outline-dark" id="checkout">
                                Proceed to checkout
                            </button>
                        </form>
                        {% else %}
                        <a type="submit" href="{% url 'add_address' %}"
                           class="btn btn-dark btn-outline-dark">
                            Create an address before checkout
                        </a>
                        {% endif %}
                        {% else %}

                        <a type="submit" href="{% url 'login' %}"
                           class="btn btn-dark btn-lg btn-outline-dark">
                            Proceed to checkout
                        </a>
                        {% endif %}

                    </div>
                </div>
            </div>

        </div>
    </section>

    {% else %}

    <div class="text-center py-5">
        <h3 class="mb-3">Your cart is empty.</h3>
        <a href="{% url 'products:category' %}"><i class="fas fa-long-arrow-alt-left mr-2"> </i>Continue shopping</a>
    </div>

    {% endif %}

</div>
{% endblock content %}

{% block script %}
<script>
$(document).ready(function(){
    $("#checkout").on('click',function(e){

        if( !$('.address').is(':checked') ) {
            e.preventDefault();
            alert("Please select an address for checkout this order.!");
        }

    });
});

</script>
{% endblock script %}

templates/products/categories.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<!-- HERO SECTION-->
<div class="container">


    <!-- CATEGORIES SECTION-->
    <section class="pt-5">
        <header class="text-center">
            <p class="small text-muted small text-uppercase mb-1">Carefully created collections</p>
            <h2 class="h5 text-uppercase mb-4">Browse our categories</h2>
        </header>
        <div class="row">
            {% if categories_obj %}
            {% for category in categories_obj %}

            <div class="col-md-4 mb-4 mb-md-5">
                <a class="category-item" href="{{ category.get_url }}">
                    {% if category.image %}
                    <img class="img-fluid" src="{{ category.image.url }}" alt="{{ category.title }}">
                    {% else %}
                    <img class="img-fluid" src="{% static 'img/cat-img.jpg' %}" alt="{{ category.title }}">
                    {% endif %}
                    <strong class="category-item-title">{{ category.title }}</strong>
                </a>
            </div>

            {% endfor %}
            {% endif %}
        </div>
    </section>


    <!-- SERVICES-->
    <section class="py-5 bg-light">
        <div class="container">
            <div class="row text-center">
                <div class="col-lg-4 mb-3 mb-lg-0">
                    <div class="d-inline-block">
                        <div class="media align-items-end">
                            <svg class="svg-icon svg-icon-big svg-icon-light">
                                <use xlink:href="#delivery-time-1"></use>
                            </svg>
                            <div class="media-body text-left ml-3">
                                <h6 class="text-uppercase mb-1">Free shipping</h6>
                                <p class="text-small mb-0 text-muted">Free shipping worldwide</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 mb-3 mb-lg-0">
                    <div class="d-inline-block">
                        <div class="media align-items-end">
                            <svg class="svg-icon svg-icon-big svg-icon-light">
                                <use xlink:href="#helpline-24h-1"></use>
                            </svg>
                            <div class="media-body text-left ml-3">
                                <h6 class="text-uppercase mb-1">24 x 7 service</h6>
                                <p class="text-small mb-0 text-muted">Free shipping worldwide</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="d-inline-block">
                        <div class="media align-items-end">
                            <svg class="svg-icon svg-icon-big svg-icon-light">
                                <use xlink:href="#label-tag-1"></use>
                            </svg>
                            <div class="media-body text-left ml-3">
                                <h6 class="text-uppercase mb-1">Festival offer</h6>
                                <p class="text-small mb-0 text-muted">Free shipping worldwide</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>


    <!-- NEWSLETTER-->
    <section class="py-5">
        <div class="container p-0">
            <div class="row">
                <div class="col-lg-6 mb-3 mb-lg-0">
                    <h5 class="text-uppercase">Let's be friends!</h5>
                    <p class="text-small text-muted mb-0">Nisi nisi tempor consequat laboris nisi.</p>
                </div>
                <div class="col-lg-6">
                    <form action="#">
                        <div class="input-group flex-column flex-sm-row mb-3">
                            <input class="form-control form-control-lg py-3" type="email"
                                   placeholder="Enter your email address" aria-describedby="button-addon2">
                            <div class="input-group-append">
                                <button class="btn btn-dark btn-block" id="button-addon2" type="submit">Subscribe
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
</div>

{% endblock content %}