core_folder/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('user/', include('account.urls')),
    path('orders/', include('orders.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'account.views.handle_not_fount'

orders/urls.py
from django.urls import path

from orders import views

urlpatterns = [
    path('proceed-to-checkout', views.checkout, name='checkout'),
    path('handle-request', views.handle_request, name='handle_request'),
    path('my-orders', views.orders, name='orders'),
    path('my-orders/<int:o_id>', views.order_detail, name='order_detail'),
    path('generate-invoice/<int:o_id>/Payment-Invoice', views.generate_invoice, name='generate_invoice'),
]

products/urls.py
from django.urls import path
from django.views.generic import TemplateView

from products import views

app_name = 'products'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('categories/', TemplateView.as_view(template_name='products/categories.html'), name='category'),
    path('category/<slug:category_slug>/', views.product_list, name='products-list'),
    path('product/<slug:c_slug>/<slug:p_slug>/', views.details_of_product, name='category'),
    path('cart/', views.cart, name='cart'),
    path('add-to-cart/', views.add_to_cart, name='add_to_cart'),
    path('minus-from-cart/', views.minus_from_cart, name='minus_from_cart'),
    path('remove-from-cart/<str:p_id>/', views.remove_from_cart, name='remove_from_cart'),
]

orders/models.py
from django.db import models
from django.utils import timezone

from account.models import CustomUser, Address
from products.models import Product


class Order(models.Model):
    status_choices = (
        (1, 'Order Confirmed'),
        (2, 'Shipped'),
        (3, 'Delivered')
    )
    payment_status_choices = (
        (1, 'SUCCESS'),
        (2, 'FAILURE'),
        (3, 'PENDING'),
    )

    order_id = models.CharField(unique=True, max_length=50, null=True, blank=True, default=None)

    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    address = models.ForeignKey(Address, on_delete=models.CASCADE)

    sub_total = models.FloatField()
    tax = models.FloatField()
    shipping_charge = models.FloatField()
    discount = models.FloatField()
    grand_total = models.FloatField()

    order_status = models.IntegerField(choices=status_choices, default=1)
    payment_status = models.IntegerField(choices=payment_status_choices, default=3)
    datetime_of_payment = models.DateTimeField(default=timezone.now)

    # related to razorpay
    razorpay_order_id = models.CharField(max_length=150, null=True, blank=True)
    razorpay_payment_id = models.CharField(max_length=150, null=True, blank=True)
    razorpay_signature = models.CharField(max_length=150, null=True, blank=True)

    def save(self, *args, **kwargs):
        if self.order_id is None and self.datetime_of_payment and self.pk:
            self.order_id = self.datetime_of_payment.strftime('%y%m%dODR') + str(self.pk)
        return super().save(*args, **kwargs)

    def __str__(self):
        return str(self.user) + "|" + str(self.order_id)


class ProductInOrder(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    price = models.FloatField(null=True, blank=True, default=None)

    def save(self, *args, **kwargs):
        self.price = self.product.price * self.quantity
        return super().save(*args, **kwargs)

    class Meta:
        unique_together = (('order', 'product'),)

orders/views.py
from io import BytesIO

import razorpay
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.template.loader import get_template
from django.views.decorators.csrf import csrf_exempt
from xhtml2pdf import pisa

from account.models import Address
from core_folder import settings
from orders.models import Order, ProductInOrder
from products.models import Cart, Product

razorpay_client = razorpay.Client(auth=(settings.RAZORPAY_ID, settings.RAZORPAY_KEY))


@login_required(login_url='login')
def checkout(request):
    address_id = request.GET['address']
    address = get_object_or_404(Address, id=address_id)
    cart_objs = Cart.objects.filter(user=request.user)

    sub_total = 0
    for i in cart_objs:
        sub_total += i.item_total()

    tax = sub_total * 3 / 100  # 3% tax
    shipping_charge = 40
    discount = sub_total * 2 / 100  # 2% discount
    grand_total = sub_total + tax + shipping_charge - discount

    notes = {'order-type': "basic order from the website", 'key': 'value'}
    razorpay_order = razorpay_client.order.create(dict(amount=int(grand_total * 100), notes=notes, currency="INR"))

    Order.objects.create(
        user=request.user,
        address=address,
        sub_total=sub_total,
        tax=tax,
        shipping_charge=shipping_charge,
        discount=discount,
        grand_total=grand_total,
        razorpay_order_id=razorpay_order['id']
    ).save()

    context = {
        'address': address,
        'cart_objs': cart_objs,
        'sub_total': sub_total,
        'tax': tax,
        'shipping_charge': shipping_charge,
        'discount': discount,
        'grand_total': grand_total,
        'razorpay_id': settings.RAZORPAY_ID,
        'order_id': razorpay_order['id'],
        'currency': razorpay_order['currency'],
    }
    return render(request, 'orders/checkout.html', context)


@login_required(login_url='login')
@csrf_exempt
def handle_request(request):
    if request.method == 'POST':
        try:
            params_dict = {
                'razorpay_order_id': request.POST['razorpay_order_id'],
                'razorpay_payment_id': request.POST['razorpay_payment_id'],
                'razorpay_signature': request.POST['razorpay_signature'],
            }
            razorpay_client.utility.verify_payment_signature(params_dict)

            order = get_object_or_404(Order, razorpay_order_id=params_dict['razorpay_order_id'])
            order.razorpay_payment_id = params_dict['razorpay_payment_id']
            order.razorpay_signature = params_dict['razorpay_signature']
            order.payment_status = 1  # 1 for success status
            order.save()

            cart_item = Cart.objects.filter(user=request.user)
            for item in cart_item:
                ProductInOrder.objects.create(
                    order=order,
                    product=item.product,
                    quantity=item.quantity,
                ).save()

                product = get_object_or_404(Product, id=item.product.id)
                product.stock -= item.quantity
                product.save()

            cart_item.delete()

            context = {
                'status': True,
                'order': order,
            }

            return render(request, 'orders/payment_status.html', context)
        except:
            return render(request, 'orders/payment_status.html', {'status': False})
    else:
        return redirect('products:cart')


@login_required(login_url='login')
def orders(request):
    return render(request, 'orders/orders.html', {'orders': Order.objects.filter(user=request.user, payment_status=1)})


@login_required(login_url='login')
def order_detail(request, o_id):
    order = get_object_or_404(Order, id=o_id)
    context = {
        'order': order,
        'products': ProductInOrder.objects.filter(order=order)
    }
    return render(request, 'orders/order_detail.html', context)


def render_to_pdf(template_src, context_dict):
    template = get_template(template_src)
    html = template.render(context_dict)
    result = BytesIO()
    pdf = pisa.pisaDocument(BytesIO(html.encode("ISO-8859-1")), result)
    if not pdf.err:
        return HttpResponse(result.getvalue(), content_type='application/pdf')
    return None


@login_required(login_url='login')
def generate_invoice(request, o_id):
    try:
        order = Order.objects.get(id=o_id, user=request.user, payment_status=1)
    except:
        return HttpResponse("<h1>505 Not Found</h1>")

    data = {
        'order_id': order.order_id,
        'order': order,
        'date': order.datetime_of_payment.strftime("%b %d %Y"),
        'transaction_id': order.razorpay_payment_id,
    }

    pdf = render_to_pdf('orders/invoice.html', data)
    return HttpResponse(pdf, content_type='application/pdf')

templates/orders/invoice.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Invoice Digital Ground</title>
    <style>
        body {
            font-size: 13px;
            margin: 30px 50px;
        }

        table {
            width: 100%;
        }

        .heading {
            background-color: #f4f4f4;
            padding-top: 5px;
        }

        .styled-table thead tr {
            background-color: #dcb14a;
            color: #000000;
            text-align: left;
            font-size: 15px;
            font-weight: bold;
        }

        .styled-table th,
        .styled-table td {
            padding: 5px 15px 0 15px;
        }

        .styled-table tbody tr {
            border-bottom: 1px solid #dddddd;
        }

        .styled-table tbody tr:nth-of-type(even) {
            background-color: #f3f3f3;
        }

        .styled-table tbody tr:last-of-type {
            border-bottom: 1px solid #dcb14a;
        }

    </style>

</head>

<body>

<table>
    <tr>
        <td colspan="2"></td>
        <td>
            <p>
                <strong style="font-size: 20px;">Digital Ground</strong><br>
                Panampilly Nagar,<br>
                Kochi, Kerala 682036 <br>
                PH: 04843777777<br>
            </p>
        </td>
    </tr>
</table>
<table>
    <tr class="heading">
        <td></td>
        <td style="font-size: 18px;"><strong>Invoice</strong></td>
        <td></td>
    </tr>
    <tr style="padding-top: 10px;">
        <td>
            PH:&nbsp;{{ order.address.phone_number }} <br>
            {{ order.address.locality }} {{ order.address.pin_code }} <br>
            {{ order.address.district }} <br>
            {{ order.address.state }}
        </td>
        <td style="padding: 0;" colspan="2" align="right">
            Order Number: <span style="color:#dcb14a;">#{{ order_id }}</span> <br>
            Order Date: {{ date }} <br>
            Transaction Id: {{ transaction_id }}
        </td>
    </tr>
</table>


<table class="styled-table">
    <thead>
    <tr>
        <td>Product</td>
        <td>Qty</td>
        <td>Price</td>
    </tr>
    </thead>
    <tbody>
    {% for product in order.productinorder_set.all %}
    <tr>
        <td>{{ product.product.title }}</td>
        <td>{{ product.quantity }}</td>
        <td>{{ product.price }}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>

<table>
    <tbody>
    <tr>
        <td colspan="1"></td>
        <td>
            <table class="styled-table">
                <tr style="font-size: 15px">
                    <td>
                        Sub&nbsp;total
                        Shipping&nbsp;charge
                        Tax
                        Discount
                        <strong>Grand&nbsp;total</strong>
                    </td>
                    <td>
                        {{ order.sub_total }}
                        +&nbsp;{{ order.shipping_charge }}
                        +&nbsp;{{ order.tax }}
                        -&nbsp;{{ order.discount }}
                        <strong>{{ order.grand_total }}</strong>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
    </tbody>
</table>
<hr>
<strong>Estimated Time:</strong> <br>
Minimum 2 working days <br>
Maximum 5 to 10 working days <br>
Product dispatch is only after complete product manufacturing. <br><br>
*All values are in INR
</body>

</html>

templates/orders/order_detail.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block content %}
<div class="container">

    <!-- HERO SECTION-->
    <section class="py-5 bg-light">
        <div class="container">
            <div class="row px-4 px-lg-5 py-lg-4 align-items-center">
                <div class="col-lg-6">
                    <h1 class="h2 text-uppercase mb-0">My Order detail</h1>
                </div>
                <div class="col-lg-6 text-lg-right">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb justify-content-lg-end mb-0 px-0">
                            <li class="breadcrumb-item"><a href="{% url 'products:home' %}">Home</a></li>
                            <li class="breadcrumb-item"><a href="{% url 'orders' %}">Orders</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Order detail</li>
                        </ol>
                    </nav>
                </div>
            </div>
            {% include 'partials/_messages.html' %}
        </div>
    </section>

    {% if products %}
    <section class="py-5">
        <div class="row">
            <div class="col-lg-10 mb-lg-0 m-auto">
                <!-- Products TABLE-->
                <div class="table-responsive mb-4">
                    <table class="table">
                        <thead class="bg-light">
                        <tr>
                            <th class="border-0" scope="col">#</th>
                            <th class="border-0" scope="col">
                                <strong class="text-small text-uppercase">Title</strong>
                            </th>
                            <th class="border-0" scope="col">
                                <strong class="text-small text-uppercase">Price</strong>
                            </th>
                            <th class="border-0" scope="col">
                                <strong class="text-small text-uppercase">Quantity</strong>
                            </th>
                            <th class="border-0" scope="col">
                                <strong class="text-small text-uppercase">Total</strong>
                            </th>
                        </tr>
                        </thead>

                        <tbody>

                        {% for product in products %}
                        <tr>
                            <td class="align-middle border-0">
                                <strong class="mb-0">{{ forloop.counter }}</strong>
                            </td>
                            <td class="align-middle border-0">
                                <div class="media align-items-center">

                                    <a class="reset-anchor d-block animsition-link"
                                       href="{{ product.product.get_url }}">
                                        <img src="{{ product.product.image.url }}"
                                             alt="{{ product.product.title }}" width="70"/>
                                    </a>

                                    <div class="media-body ml-3">
                                        <strong class="h6">
                                            <a class="reset-anchor animsition-link"
                                               href="{{ product.product.get_url }}">
                                                {{ product.product.title }}
                                            </a>
                                        </strong>
                                    </div>
                                </div>
                            </td>
                            <td class="align-middle border-0">
                                <p class="mb-0 small">{{ product.product.price }}</p>
                            </td>
                            <td class="align-middle border-0">
                                <p class="mb-0 small">{{ product.quantity }}</p>
                            </td>
                            <td class="align-middle border-0">
                                <p class="mb-0 small">{{ product.price }}</p>
                            </td>
                        </tr>
                        {% endfor %}

                        </tbody>
                    </table>
                </div>

                <!-- Amount TABLE-->
                <div class="table-responsive mb-4">
                    <table class="table">
                        <thead class="bg-light">
                        <tr>
                            <th class="border-0" scope="col">
                                <strong class="text-small text-uppercase">Date</strong>
                            </th>
                            <th class="border-0" scope="col">
                                <strong class="text-small text-uppercase">sub total</strong>
                            </th>
                            <th class="border-0" scope="col">
                                <strong class="text-small text-uppercase">tax</strong>
                            </th>
                            <th class="border-0" scope="col">
                                <strong class="text-small text-uppercase">shipping charge</strong>
                            </th>
                            <th class="border-0" scope="col">
                                <strong class="text-small text-uppercase">discount</strong>
                            </th>
                            <th class="border-0" scope="col">
                                <strong class="text-small text-uppercase">Grant total</strong>
                            </th>
                        </tr>
                        </thead>

                        <tbody>

                        <tr>
                            <td class="align-middle border-0">
                                <p class="mb-0 text-capitalize">{{ order.datetime_of_payment|naturalday }}</p>
                            </td>
                            <td class="align-middle border-0">
                                <p class="mb-0 small">&#x20B9 {{ order.sub_total }}</p>
                            </td>
                            <td class="align-middle border-0">
                                <p class="mb-0 small">+ {{ order.tax }} &#x20B9</p>
                            </td>
                            <td class="align-middle border-0">
                                <p class="mb-0 small">+ {{ order.shipping_charge }} &#x20B9</p>
                            </td>
                            <td class="align-middle border-0">
                                <p class="mb-0 small">- {{ order.discount }} &#x20B9</p>
                            </td>
                            <td class="align-middle border-0">
                                <strong class="mb-0">&#x20B9 {{ order.grand_total }}</strong>
                            </td>
                        </tr>

                        </tbody>
                    </table>
                </div>
                <!-- CART NAV-->
                <div class="bg-light px-4 py-3">
                    <div class="row align-items-center text-center">
                        <div class="m-auto">
                            <a class="btn btn-primary btn-sm signup-button" target="_blank"
                               href="{% url 'generate_invoice' order.id %}">
                                Get Invoice
                            </a>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </section>

    {% else %}

    <div class="text-center py-5">
        <h3 class="mb-3">Your Order list is empty.</h3>
        <a href="{% url 'products:category' %}"><i class="fas fa-long-arrow-alt-left mr-2"> </i>Continue shopping</a>
    </div>

    {% endif %}

</div>
{% endblock content %}

templates/orders/orders.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block content %}
<div class="container">

    <!-- HERO SECTION-->
    <section class="py-5 bg-light">
        <div class="container">
            <div class="row px-4 px-lg-5 py-lg-4 align-items-center">
                <div class="col-lg-6">
                    <h1 class="h2 text-uppercase mb-0">My Orders list</h1>
                </div>
                <div class="col-lg-6 text-lg-right">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb justify-content-lg-end mb-0 px-0">
                            <li class="breadcrumb-item"><a href="{% url 'products:home' %}">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Order</li>
                        </ol>
                    </nav>
                </div>
            </div>
            {% include 'partials/_messages.html' %}
        </div>
    </section>

    {% if orders %}
    <section class="py-5">
        <div class="row">
            <div class="col-lg-10 mb-lg-0 m-auto">
                <!-- CART TABLE-->
                <div class="table-responsive mb-4">
                    <table class="table">
                        <thead class="bg-light">
                        <tr>
                            <th class="border-0" scope="col">#</th>
                            <th class="border-0" scope="col">
                                <strong class="text-small text-uppercase">Order Id</strong>
                            </th>
                            <th class="border-0" scope="col">
                                <strong class="text-small text-uppercase">Date</strong>
                            </th>
                            <th class="border-0" scope="col">
                                <strong class="text-small text-uppercase">Status</strong>
                            </th>
                            <th class="border-0" scope="col">
                                <strong class="text-small text-uppercase">Total</strong>
                            </th>
                            <th class="border-0" scope="col">
                                <strong class="text-small text-uppercase">Action</strong>
                            </th>
                        </tr>
                        </thead>

                        <tbody>

                        {% for order in orders %}
                        <tr>
                            <td class="align-middle border-0">
                                <strong class="mb-0">{{ forloop.counter }}</strong>
                            </td>
                            <td class="align-middle border-0">
                                <a href="{% url 'order_detail' order.id %}">#{{ order.order_id }}</a>
                            </td>
                            <td class="align-middle border-0">
                                <p class="mb-0 small">{{ order.datetime_of_payment|naturalday }}</p>
                            </td>
                            <td class="align-middle border-0">
                                {% if order.order_status == 1 %}
                                <p class="mb-0 small text-success">Order Confirmed</p>
                                {% elif order.order_status == 1 %}
                                <p class="mb-0 small text-success">Shipped</p>
                                {% elif order.order_status == 1 %}
                                <p class="mb-0 small text-success">Delivered</p>
                                {% endif %}
                            </td>
                            <td class="align-middle border-0">
                                <p class="mb-0 small">&#x20B9 {{ order.grand_total|intcomma }}</p>
                            </td>
                            <td class="align-middle border-0">
                                <a href="{% url 'order_detail' order.id %}"
                                   class="btn btn-primary btn-sm signup-button">View</a>
                                <a href="{% url 'generate_invoice' order.id %}" target="_blank"
                                   class="btn btn-primary btn-sm signup-button">Invoice</a>
                            </td>
                        </tr>
                        {% endfor %}

                        </tbody>
                    </table>
                </div>
                <!-- CART NAV-->
                <div class="bg-light px-4 py-3">
                    <div class="row align-items-center text-center">
                        <div class="col-md-6 mb-3 mb-md-0 text-md-left">
                            <a class="btn btn-link p-0 text-dark btn-sm" href="">
                                <i class="fas fa-long-arrow-alt-left mr-2"></i>
                                Continue shopping
                            </a>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </section>

    {% else %}

    <div class="text-center py-5">
        <h3 class="mb-3">Your Order list is empty.</h3>
        <a href="{% url 'products:category' %}"><i class="fas fa-long-arrow-alt-left mr-2"> </i>Continue shopping</a>
    </div>

    {% endif %}

</div>
{% endblock content %}

templates/orders/payment_status.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <!-- HERO SECTION-->
    <section class="bg-light">
        <div class="container">
            <div class="row px-4 px-lg-5 py-lg-4 align-items-center">
                <div class="m-auto">
                    <h1 class="h2 text-uppercase mb-0">Payment Status</h1>
                </div>
            </div>
        </div>
    </section>

    <section class="py-5">
        {% if status %}
        <div class="row">
            <div class="col-12 text-center">
                <i class="fa fa-check-circle" aria-hidden="true" style="font-size: 180px; color: rgb(30, 222, 75);"></i>
                <h3 class="mt-3">
                    Congratulations! You have successfully done the payment.<br>
                    Your order will reach to you in 5 days.
                </h3>
                <a class="btn btn-primary btn-sm signup-button my-3" target="_blank"
                   href="{% url 'generate_invoice' order.id %}">Print Invoice</a>
                <br>
                <a class="btn btn-link p-0 text-dark btn-sm" href="{% url 'products:category' %}">
                    <i class="fas fa-long-arrow-alt-left mr-2"></i>
                    Continue shopping
                </a>
            </div>
        </div>
        {% else %}
        <div class="row m-auto">
            <div class="col-12 text-center my-5">
                <h2>Oops! Payment Failed</h2>
                <a class="btn btn-primary btn-sm signup-button my-3" href="{% url 'products:cart' %}">Back to cart</a>
            </div>
        </div>
        {% endif %}
    </section>
</div>
{% endblock %}